config/routes.rb
Rails.application.routes.draw do
  root 'laboratorios#index'
  
  get 'mision-vision', to: 'main#mision'
  get 'contacto', to: 'main#contacto'
  post 'contacto', to: 'main#create_contacto'
  delete 'contacto/:id', to: 'main#delete_contacto'

  delete 'laboratorios/:id/horario', to: 'laboratorios#reset_horario'

  devise_for :users
  resources :docentes, only: [:index, :create, :destroy]
  resources :matters
  resources :horarios
  resources :laboratorios
end

app/models/horario.rb
class Horario < ApplicationRecord
  belongs_to :laboratorio
  #belongs_to :matter
  validates :laboratorio_id, uniqueness: { scope: [:dia, :hora], message: "Ya existe una clase en este laboratorio con el mismo horario" }
end

app/controllers/horarios_controller.rb
class HorariosController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  skip_before_action :verify_authenticity_token
  before_action :set_horario, only: [:show, :edit, :update, :destroy]
  before_action :horarios_active

  # GET /horarios
  # GET /horarios.json
  def index
    @horarios = Horario.all
  end

  # GET /horarios/1
  # GET /horarios/1.json
  def show
  end

  # GET /horarios/new
  def new
    @horario = Horario.new
  end

  # GET /horarios/1/edit
  def edit
  end

  # POST /horarios
  # POST /horarios.json
  def create
    @horario = Horario.new(horario_params)

    respond_to do |format|
      if @horario.save
        format.html { redirect_to @horario, notice: 'Horario was successfully created.' }
        format.json { render :show, status: :created, location: @horario }
      else
        format.html { render :new }
        format.json { render json: @horario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horarios/1
  # PATCH/PUT /horarios/1.json
  def update
    if @horario.user_id == nil || @horario.user_id == current_user.id || current_user.is_admin?
      params[:user_id] && current_user.is_admin? ? @horario.user_id = params[:user_id] : @horario.user_id = current_user.id

      respond_to do |format|
        if @horario.update(horario_params)
          format.html { redirect_to "/laboratorios/#{@horario.laboratorio_id}", notice: 'Horario actualizado' }
          format.json { render :show, status: :ok, location: @horario }
        end
      end

    else
      redirect_to "/laboratorios/#{@horario.laboratorio_id}", alert: 'Horario ocupado' 
    end
  end

  # DELETE /horarios/1
  # DELETE /horarios/1.json
  def destroy
    laboratorio_id = @horario.laboratorio_id
    @horario.update(asunto: nil, nota: nil, user_id: nil)
    respond_to do |format|
      format.html { redirect_to "/laboratorios/#{laboratorio_id}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horario
      @horario = Horario.find(params[:id])
    end

    def horarios_active
      @horarios_active = 'active'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def horario_params
      params.require(:horario).permit(:dia, :hora, :laboratorio_id, :asunto, :nota)
    end
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/views/horarios/_form.html.erb
<%= form_with(model: horario, local: true) do |form| %>
  <% if horario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(horario.errors.count, "error") %> prohibited this horario from being saved:</h2>

      <ul>
      <% horario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :matter_id %>
    <%= form.select :matter_id, Matter.all.collect { |m| [ m.nombre, m.id ] } %>
  </div>

  <div class="field">
    <%= form.label :matter_id %>
    <%= form.text_field :asunto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/horarios/edit.html.erb
<h1>Editing Horario</h1>

<%= render 'form', horario: @horario %>

<%= link_to 'Show', @horario %> |
<%= link_to 'Back', horarios_path %>

app/views/horarios/index.html.erb
<h1 class="my-4">Horarios</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Dia</th>
      <th>Hora</th>
      <th>Laboratorio</th>
      <th>Materia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @horarios.each do |horario| %>
      <tr>
        <td><%= horario.dia %></td>
        <td><%= horario.hora %></td>
        <td><%= horario.laboratorio.nombre %></td>
        <td><%= horario.asunto %></td>
        <td><%= link_to 'Edit', edit_horario_path(horario) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Horario', new_horario_path %>

app/views/horarios/new.html.erb
<h1>New Horario</h1>

<%= form_with(model: @horario, local: true) do |form| %>
  <% if @horario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@horario.errors.count, "error") %> prohibited this horario from being saved:</h2>

      <ul>
      <% @horario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dia %>
    <% semana = [{value: 'lu', nombre: 'Lunes'}, {value: 'ma', nombre: 'Martes'}, {value: 'mi', nombre: 'Miércoles'}, {value: 'ju', nombre: 'Jueves'}, {value: 'vi', nombre: 'Viernes'}, {value: 'sa', nombre: 'Sábado'}] %>
    <%= form.select :dia, semana.collect { |d| [ d[:nombre], d[:value] ] } %>
  </div>

  <div class="field">
    <%= form.label :hora %>
    <%= form.text_field :hora %>
  </div>

  <div class="field">
    <%= form.label :laboratorio_id %>
    <%= form.select :laboratorio_id, Laboratorio.all.collect { |l| [ l.nombre, l.id ] } %>
  </div>

  <div class="field">
    <%= form.label :matter_id %>
    <%= form.select :matter_id, Matter.all.collect { |m| [ m.nombre, m.id ] } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', horarios_path %>

app/views/horarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dia:</strong>
  <%= @horario.dia %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @horario.hora %>
</p>

<p>
  <strong>Laboratorio:</strong>
  <%= @horario.laboratorio.nombre %>
</p>


<%= link_to 'Edit', edit_horario_path(@horario) %> |
<%= link_to 'Back', horarios_path %>