config/routes.rb
Rails.application.routes.draw do
  root 'laboratorios#index'
  
  get 'mision-vision', to: 'main#mision'
  get 'contacto', to: 'main#contacto'
  post 'contacto', to: 'main#create_contacto'
  delete 'contacto/:id', to: 'main#delete_contacto'

  delete 'laboratorios/:id/horario', to: 'laboratorios#reset_horario'

  devise_for :users
  resources :docentes, only: [:index, :create, :destroy]
  resources :matters
  resources :horarios
  resources :laboratorios
end

app/models/matter.rb
class Matter < ApplicationRecord
    has_many :horarios
    #belongs_to :user
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
  before_action :set_matter, only: [:show, :edit, :update, :destroy]
  before_action :matters_active

  # GET /matters
  # GET /matters.json
  def index
    @matters = Matter.all
  end

  # GET /matters/1
  # GET /matters/1.json
  def show
  end

  # GET /matters/new
  def new
    @matter = Matter.new
  end

  # GET /matters/1/edit
  def edit
  end

  # POST /matters
  # POST /matters.json
  def create
    @matter = Matter.new(matter_params)

    respond_to do |format|
      if @matter.save
        format.html { redirect_to @matter, notice: 'Matter was successfully created.' }
        format.json { render :show, status: :created, location: @matter }
      else
        format.html { render :new }
        format.json { render json: @matter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matters/1
  # PATCH/PUT /matters/1.json
  def update
    respond_to do |format|
      if @matter.update(matter_params)
        format.html { redirect_to @matter, notice: 'Matter was successfully updated.' }
        format.json { render :show, status: :ok, location: @matter }
      else
        format.html { render :edit }
        format.json { render json: @matter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matters/1
  # DELETE /matters/1.json
  def destroy
    @matter.destroy
    respond_to do |format|
      format.html { redirect_to matters_url, notice: 'Matter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matter
      @matter = Matter.find(params[:id])
    end

    def matters_active
      @matters_active = 'active'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def matter_params
      params.require(:matter).permit(:nombre)
    end
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/views/matters/_form.html.erb
<%= form_with(model: matter, local: true) do |form| %>
  <% if matter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(matter.errors.count, "error") %> prohibited this matter from being saved:</h2>

      <ul>
      <% matter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/matters/edit.html.erb
<h1>Editing Matter</h1>

<%= render 'form', matter: @matter %>

<%= link_to 'Show', @matter %> |
<%= link_to 'Back', matters_path %>

app/views/matters/index.html.erb
<h1 class="my-4">Materias</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @matters.each do |matter| %>
      <tr>
        <td><%= matter.nombre %></td>
        <td><%= link_to 'Editar', edit_matter_path(matter) %></td>
        <td><%= link_to 'Eliminar', matter, method: :delete, data: { confirm: '¿Seguro de querer eliminar esta materia?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Matter', new_matter_path %>

app/views/matters/new.html.erb
<h1>New Matter</h1>

<%= render 'form', matter: @matter %>

<%= link_to 'Back', matters_path %>

app/views/matters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @matter.nombre %>
</p>

<%= link_to 'Edit', edit_matter_path(@matter) %> |
<%= link_to 'Back', matters_path %>