config/routes.rb
Rails.application.routes.draw do
  root 'laboratorios#index'
  
  get 'mision-vision', to: 'main#mision'
  get 'contacto', to: 'main#contacto'
  post 'contacto', to: 'main#create_contacto'
  delete 'contacto/:id', to: 'main#delete_contacto'

  delete 'laboratorios/:id/horario', to: 'laboratorios#reset_horario'

  devise_for :users
  resources :docentes, only: [:index, :create, :destroy]
  resources :matters
  resources :horarios
  resources :laboratorios
end

app/models/laboratorio.rb
class Laboratorio < ApplicationRecord
    has_many :horarios
end

app/controllers/laboratorios_controller.rb
class LaboratoriosController < ApplicationController
  before_action :have_permissions?, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_laboratorio, only: [:show, :edit, :update, :destroy, :reset_horario]
  before_action :laboratorios_active

  # GET /laboratorios
  # GET /laboratorios.json
  def index
    @laboratorios = Laboratorio.all
  end

  # GET /laboratorios/1
  # GET /laboratorios/1.json
  def show
    horarios = Horario.where(laboratorio_id: @laboratorio.id)
    @horario = Hash.new
    @users = User.all
    
    horarios.each do |h|
      key = "#{h[:dia]}#{h[:hora].gsub '-', ''}"
      @horario[:"#{key}"] = { id: h.id, asunto: h.asunto, user_id: h.user_id }
    end

    #raise @horario.to_yaml
  end

  # GET /laboratorios/new
  def new
    @laboratorio = Laboratorio.new
  end

  # GET /laboratorios/1/edit
  def edit
  end

  # POST /laboratorios
  # POST /laboratorios.json
  def create
    @laboratorio = Laboratorio.new(laboratorio_params)
    horario = [
      {dia: 'lu', hora: '7-8'}, {dia: 'lu', hora: '8-9'}, {dia: 'lu', hora: '9-10'}, {dia: 'lu', hora: '10-11'}, {dia: 'lu', hora: '11-12'}, {dia: 'lu', hora: '12-13'}, {dia: 'lu', hora: '13-14'}, {dia: 'lu', hora: '14-15'}, {dia: 'lu', hora: '15-16'}, {dia: 'lu', hora: '16-17'}, {dia: 'lu', hora: '17-18'}, {dia: 'lu', hora: '18-19'}, {dia: 'lu', hora: '19-20'}, {dia: 'lu', hora: '20-21'}, {dia: 'lu', hora: '21-22'},
      {dia: 'ma', hora: '7-8'}, {dia: 'ma', hora: '8-9'}, {dia: 'ma', hora: '9-10'}, {dia: 'ma', hora: '10-11'}, {dia: 'ma', hora: '11-12'}, {dia: 'ma', hora: '12-13'}, {dia: 'ma', hora: '13-14'}, {dia: 'ma', hora: '14-15'}, {dia: 'ma', hora: '15-16'}, {dia: 'ma', hora: '16-17'}, {dia: 'ma', hora: '17-18'}, {dia: 'ma', hora: '18-19'}, {dia: 'ma', hora: '19-20'}, {dia: 'ma', hora: '20-21'}, {dia: 'ma', hora: '21-22'},
      {dia: 'mi', hora: '7-8'}, {dia: 'mi', hora: '8-9'}, {dia: 'mi', hora: '9-10'}, {dia: 'mi', hora: '10-11'}, {dia: 'mi', hora: '11-12'}, {dia: 'mi', hora: '12-13'}, {dia: 'mi', hora: '13-14'}, {dia: 'mi', hora: '14-15'}, {dia: 'mi', hora: '15-16'}, {dia: 'mi', hora: '16-17'}, {dia: 'mi', hora: '17-18'}, {dia: 'mi', hora: '18-19'}, {dia: 'mi', hora: '19-20'}, {dia: 'mi', hora: '20-21'}, {dia: 'mi', hora: '21-22'},
      {dia: 'ju', hora: '7-8'}, {dia: 'ju', hora: '8-9'}, {dia: 'ju', hora: '9-10'}, {dia: 'ju', hora: '10-11'}, {dia: 'ju', hora: '11-12'}, {dia: 'ju', hora: '12-13'}, {dia: 'ju', hora: '13-14'}, {dia: 'ju', hora: '14-15'}, {dia: 'ju', hora: '15-16'}, {dia: 'ju', hora: '16-17'}, {dia: 'ju', hora: '17-18'}, {dia: 'ju', hora: '18-19'}, {dia: 'ju', hora: '19-20'}, {dia: 'ju', hora: '20-21'}, {dia: 'ju', hora: '21-22'},
      {dia: 'vi', hora: '7-8'}, {dia: 'vi', hora: '8-9'}, {dia: 'vi', hora: '9-10'}, {dia: 'vi', hora: '10-11'}, {dia: 'vi', hora: '11-12'}, {dia: 'vi', hora: '12-13'}, {dia: 'vi', hora: '13-14'}, {dia: 'vi', hora: '14-15'}, {dia: 'vi', hora: '15-16'}, {dia: 'vi', hora: '16-17'}, {dia: 'vi', hora: '17-18'}, {dia: 'vi', hora: '18-19'}, {dia: 'vi', hora: '19-20'}, {dia: 'vi', hora: '20-21'}, {dia: 'vi', hora: '21-22'},
      {dia: 'sa', hora: '7-8'}, {dia: 'sa', hora: '8-9'}, {dia: 'sa', hora: '9-10'}, {dia: 'sa', hora: '10-11'}, {dia: 'sa', hora: '11-12'}, {dia: 'sa', hora: '12-13'}, {dia: 'sa', hora: '13-14'}, {dia: 'sa', hora: '14-15'}, {dia: 'sa', hora: '15-16'}, {dia: 'sa', hora: '16-17'}, {dia: 'sa', hora: '17-18'}, {dia: 'sa', hora: '18-19'}, {dia: 'sa', hora: '19-20'}, {dia: 'sa', hora: '20-21'}, {dia: 'sa', hora: '21-22'}
    ]
    horario.each do |h|
      @laboratorio.horarios.new(dia: h[:dia], hora: h[:hora])
    end

    respond_to do |format|
      if @laboratorio.save
        format.html { redirect_to @laboratorio, notice: 'Laboratorio creado' }
        format.json { render :show, status: :created, location: @laboratorio }
      else
        format.html { render :new }
        format.json { render json: @laboratorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laboratorios/1
  # PATCH/PUT /laboratorios/1.json
  def update
    respond_to do |format|
      if @laboratorio.update(laboratorio_params)
        format.html { redirect_to @laboratorio, notice: 'Laboratorio actualizado' }
        format.json { render :show, status: :ok, location: @laboratorio }
      else
        format.html { render :edit }
        format.json { render json: @laboratorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laboratorios/1
  # DELETE /laboratorios/1.json
  def destroy
    @laboratorio.horarios.destroy_all
    @laboratorio.destroy
    respond_to do |format|
      format.html { redirect_to laboratorios_url, notice: 'Laboratorio eliminado' }
      format.json { head :no_content }
    end
  end

  def reset_horario
    @laboratorio.horarios.update_all(asunto: nil, nota: nil, user_id: nil)
    respond_to do |format|
      format.html { redirect_to @laboratorio }
      format.json { head :no_content }
    end
  end

  private
    def have_permissions?
        redirect_to root_path, alert: 'No eres administrador' unless user_signed_in? && current_user.is_admin?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_laboratorio
      @laboratorio = Laboratorio.find(params[:id])
    end

    def laboratorios_active
      @laboratorios_active = 'active'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def laboratorio_params
      params.require(:laboratorio).permit(:nombre, :ubicacion, :equipos)
    end
end

app/helpers/laboratorios_helper.rb
module LaboratoriosHelper
end

app/views/laboratorios/_form.html.erb
<%= form_with(model: laboratorio, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :ubicacion,  'Ubicación' %>
    <%= form.text_field :ubicacion, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :equipos, 'Número de equipos' %>
    <%= form.number_field :equipos, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/laboratorios/edit.html.erb
<h1 class="my-4">Editar Laboratorio</h1>

<div class="col-md-8 offset-md-2">
    <%= render 'form', laboratorio: @laboratorio %>
<div>

app/views/laboratorios/index.html.erb
<h1 class="my-4">Laboratorios <%= link_to 'Nuevo laboratorio', new_laboratorio_path, class: 'btn btn-sm btn-success' if user_signed_in? && current_user.is_admin? %></h1>

<table class="table">
  <thead class="azul text-white">
    <tr>
      <th>Nombre</th>
      <th>Ubicación</th>
      <th>No. Equipos</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @laboratorios.each do |laboratorio| %>
      <tr>
        <td><%= laboratorio.nombre %></td>
        <td><%= laboratorio.ubicacion %></td>
        <td><%= laboratorio.equipos %></td>
        <td class="text-right">
          <%= link_to 'Ver horario', laboratorio, class: 'btn btn-sm btn-success' %>
          <%= link_to 'Editar', edit_laboratorio_path(laboratorio), class: 'btn btn-sm btn-info' if user_signed_in? && current_user.is_admin? %>
          <%= link_to 'Eliminar', laboratorio, method: :delete, data: { confirm: '¿Seguro de querer eliminar este laboratorio?' }, class: 'btn btn-sm btn-danger' if user_signed_in? && current_user.is_admin? %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/laboratorios/new.html.erb
<h1 class="my-4">Nuevo Laboratorio</h1>

<div class="col-md-8 offset-md-2">
    <%= render 'form', laboratorio: @laboratorio %>
</div>

app/views/laboratorios/show.html.erb
<h1 class="my-4"><%= @laboratorio.nombre %> <%= link_to 'Reiniciar horario', "/laboratorios/#{@laboratorio.id}/horario", method: :delete, class: 'btn btn-sm btn-success', data: { confirm: 'Esto eliminará todos los horarios del laboratorio, ¿desea continuar?' } %></h1>

<table class="table table-striped table-bordered text-center">
  <thead class="azul text-white">
    <tr>
      <th>Hora</th>
      <th>Lunes</th>
      <th>Martes</th>
      <th>Miércoles</th>
      <th>Jueves</th>
      <th>Vierenes</th>
      <th>Sábado</th>
    </tr>
  </thead>
  <% dias = ['lu', 'ma', 'mi', 'ju', 'vi', 'sa'] %>
  <% hora = ['78', '89', '910', '1011', '1112', '1213', '1314', '1415', '1516', '1617', '1718', '1819', '1920', '2021', '2122'] %>
  <% td = ['07:00 - 08:00', '08:00 - 09:00', '09:00 - 10:00', '10:00 - 11:00', '11:00 - 12:00', '12:00 - 13:00', '13:00 - 14:00', '14:00 - 15:00', '15:00 - 16:00', '16:00 - 17:00', '17:00 - 18:00', '18:00 - 19:00', '19:00 - 20:00', '20:00 - 21:00', '21:00 - 22:00'] %>
  <tbody>
      <% hora.each_with_index do |hora, i| %>
        <tr>
          <td><%= td[i] %></td>
          
          <% dias.each do |dia| %>
            <td>
              <% horario = @horario[:"#{dia}#{hora}"] %>
              <% if user_signed_in? %>
                <% if horario[:asunto] && (horario[:user_id] == current_user.id || current_user.is_admin? ) %>
                  <div class="dropdown">
                    <i class="fa fa-ellipsis-v cursor-poiter pt-1" style="float: right; opacity: .8;" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    </i>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="#" data-toggle="modal" data-target="#editModal" data-id="<%= horario[:id] %>">Editar</a>
                      <a class="dropdown-item" href="/horarios/<%= horario[:id] %>" data-method="delete">Eliminar</a>
                    </div>
                  </div>
                <%elsif horario[:asunto] == '' || horario[:asunto] == nil%>
                  <i class='fas fa-plus cursor-poiter' data-toggle="modal" data-target="#editModal" data-id="<%= horario[:id] %>"></i>
                <%end%>
              <%end%>
              <span class='cursor-poiter' data-toggle="modal" data-target="#showModal" data-id="<%= horario[:id] %>"><%= horario[:asunto] %></span>
            </td>
          <%end%>
        </tr>
      <%end%>
  </tbody>
</table>

<!-- Modal Editar -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title edit-title" id="editModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_tag( '/horarios/' , method: 'put', id: 'formEdit') do |f| %>
        <%= csrf_meta_tags %>
        <div class="modal-body">
          <% if user_signed_in? && current_user.is_admin? %>
            <div class="form-group">
              <label for="horario_user_id" class="col-form-label">Maestro:</label>
              <%= select_tag :user_id, options_for_select(@users.collect {|u| [ u.nombre, u.id ] }), class: 'form-control' %>
            </div>
          <%end%>
          <div class="form-group">
            <label for="horario_asunto" class="col-form-label">Asunto:</label>
            <input type="text" class="form-control" id="horario_asunto" name="horario[asunto]">
          </div>
          <div class="form-group">
            <label for="horario_nota" class="col-form-label">Nota:</label>
            <textarea class="form-control" id="horario_nota" name="horario[nota]"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <input type="submit" class="btn btn-success" value="Guardar">
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Modal Show -->
<div class="modal fade" id="showModal" tabindex="-1" role="dialog" aria-labelledby="showModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title show-title" id="showModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <div class="modal-body">
            <div class="form-group">
              <label for="horario_user_id" class="col-form-label">Maestro:</label>
              <p class="maestro"></p>
            </div>
          <div class="form-group">
            <label for="horario_asunto" class="col-form-label">Asunto:</label>
            <p class="asunto"></p>
          </div>
          <div class="form-group">
            <label for="horario_nota" class="col-form-label">Nota:</label>
            <p class="nota"></p>
          </div>
        </div>
    </div>
  </div>
</div>


<% if user_signed_in? %>
  <script>
    $('#editModal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget); // Button that triggered the modal
      var id_horario = button.data('id'); // Extract info from data-* attributes
      // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
      // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
      $.get( "/horarios/"+id_horario+".json", function( data ) {
        modal.find('.edit-title').text(data['dia']+" | "+data['hora']);
        $('#formEdit').attr('action', '/horarios/'+id_horario);
        modal.find('.modal-body input').val(data['asunto']);
        modal.find('.modal-body textarea').val(data['nota']);
      });
      
      var modal = $(this);
    })
  </script>
<%end%>

<script>
    $('#showModal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget); // Button that triggered the modal
      var id_horario = button.data('id'); // Extract info from data-* attributes
      // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
      // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
      $.get( "/horarios/"+id_horario+".json", function( data ) {
        modal.find('.show-title').text(data['dia']+" | "+data['hora']);
        $('#formEdit').attr('action', '/horarios/'+id_horario);
        modal.find('.modal-body .maestro').text(data['maestro']);
        modal.find('.modal-body .asunto').text(data['asunto']);
        modal.find('.modal-body .nota').text(data['nota']);
      });
      
      var modal = $(this);
    })
  </script>